#!/bin/bash

#
# Push the latest image, just built, to a private repository.
#
HERE=iay/md-validator-ukf:latest
THERE=registry.iay.org.uk/md-validator-ukf:latest

docker tag ${HERE} ${THERE}
docker push ${THERE}
