#
# Stack configuration for a deployment of md-validator-ukf.
#

version: "3.5"

services:

  validator:
    image: ianayoung/md-validator-ukf:latest
    entrypoint:
      - "java"
      - "-Dserver.servlet.context-path=/md-validator-basic"
      # Attend to the forwarding headers from the reverse proxy
      - "-Dserver.forward-headers-strategy=NATIVE"
      - "org.springframework.boot.loader.launch.JarLauncher"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # Enable the service
        - "traefik.enable=true"
        - "traefik.http.services.validator-basic.loadbalancer.server.port=8080"
        # https://apps.iay.org.uk/md-validator-basic
        - "traefik.http.routers.validator-basic.entrypoints=websecure"
        - "traefik.http.routers.validator-basic.tls=true"
        - "traefik.http.routers.validator-basic.tls.certResolver=le"
        - "traefik.http.routers.validator-basic.rule=Host(`apps.iay.org.uk`) && PathPrefix(`/md-validator-basic`)"
        - "traefik.http.routers.validator-basic.service=validator-basic"
        # Monitor new versions of the image
        - "diun.enable=true"

networks:
  default:
    external: true
    name: traefik

